version: 2.1

orbs:
  hugo: circleci/hugo@0.5.2

jobs:
  test:
    docker:
      - image: circleci/node:10.21.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test API JSON
          command: npm run test:json

workflows:
  build_and_test:
    jobs:
      - hugo/build:
          html-proofer: false
          version: "0.66.0"
      - test:
          requires:
            - hugo/build
